User.destroy_all
Tactic.destroy_all
UserTactic.destroy_all


#Lose weight, level 1
Tactic.create(action: "Cardio: Walk around the Central Park Resevoir", goal: "Lose Weight", fitness_level: 1, description: "This man-made lake is one of the park's most iconic running routes; many celebrities have been spotted jogging here. \n\nThis path is 1.58 mi in length and offers stunning views of the Upper West Side skyline.")
Tactic.create(action: "Cardio: Walk the High Line", goal: "Lose Weight", description: "This 1.45 mi long elevated greenway was converted from an old railway. \n\nOn this path, you will wind through soaring buildings and stand above traffic in Chelsea.", fitness_level: 1)
Tactic.create(action: "Cardio: Walk over the Brooklyn Bridge", goal: "Lose Weight", description: "Undoubtedly the most famous bridge in all of NYC - the 1 mi path will provide a steep incline to work out those leg muscles!", fitness_level: 1)
Tactic.create(action: "Cardio: Walk down Fifth Avenue", goal: "Lose Weight", description: "During this 1.5 mi walk starting at E 40th and ending on E 60th, you will see Bryant Park and the countless stores that make the street so famous. I hope you brought your credit card! \n\nAlthough, window shopping is just fine - the store front displays are a sight to see in themselves.", fitness_level: 1)
Tactic.create(action: "Cardio: Walk through Times Square", goal: "Lose Weight", description: "During this 1 mi walk starting at W 32nd and ending on W 52nd on 7th Avenue, you will see why tourists come from around the world to visit the Big Apple. \n\nDon't be afraid to venture down a side street! You may also discover Broadway, Rockefellar Center, Madame Tussauds and more!", fitness_level: 1)
Tactic.create(action: "Cardio: Walk or swim at Rockaway Beach", goal: "Lose Weight", description: "Escape the concrete jungle by stopping by this local beach in Queens! \n\nDepending on the season, you can swim continously for 30 minutes or stay dry and walk along the water's edge for at least 1.5 miles (Rockaway is 5.5 mi in length total).", fitness_level: 1)
Tactic.create(action: "Cardio: Walk around Brooklyn Bridge Park", goal: "Lose Weight", description: "Located in DUMBO, this walk offers 1.3 mi of waterfront with increible views of FiDi. \n\nPrepare for lots of pictures.", fitness_level: 1)
Tactic.create(action: "Cardio: Walk around Battery Park", goal: "Lose Weight", description: "This walk offers 1 mi of glorious waterfront. \n\nPrepare for amazing views of downtown (including the Freedom Tower) as well as the Statue of Liberty!", fitness_level: 1)
Tactic.create(action: "Cardio: Walk through Soho", goal: "Lose Weight", description: "Walk for at least 1.5 mi and have fun exploring! Soho is known for its quaint cobblestone roads that are full of designer boutiques, galleries, and restaurants. \n\nYou could easily spend all day in this neighborhood. Be careful to not twist your ankle on those old streets!", fitness_level: 1)
Tactic.create(action: "Cardio: Bike through Long Island City", goal: "Lose Weight", description: "Bike for at least 5 mi and have fun exploring! \n\nLong Island City is at the tip of Queens, offers an amazing view of Midtown, and has more dogs than your heart could ever desire!" , fitness_level: 1)

#Lose weight, level 2
Tactic.create(action: "Cardio: Jog around the Central Park Resevoir twice", goal: "Lose Weight", description: "This man-made lake is one of the park's most iconic routes; many celebrities have been spotted jogging here. \n\nThis path is 1.58 mi (X2) in length and offers stunning views of the Upper West Side skyline.", fitness_level: 2)
Tactic.create(action: "Cardio: Jog the High Line twice", goal: "Lose Weight", description: "This 1.45 mi (X2 - there and back) long elevated greenway was converted from an old railway. \n\nOn this path, you will wind through soaring buildings and stand above traffic in Chelsea.", fitness_level: 2)
Tactic.create(action: "Cardio: Jog there and back over the Brooklyn Bridge", goal: "Lose Weight", description: "Undoubtedly the most famous bridge in all of NYC - the 2 mi path will provide a steep incline to work out those leg muscles!", fitness_level: 2)
Tactic.create(action: "Cardio: Jog up and down Fifth Avenue", goal: "Lose Weight", description: "During this 3 mi jog starting at E 40th, going up to E 60th and back, you will see Bryant Park and the countless stores that make the street so famous. \n\nI hope you brought your credit card! Although, window shopping is just fine - the store front displays are a sight to see in themselves.", fitness_level: 2)
Tactic.create(action: "Cardio: Jog there and back through Times Square" , goal: "Lose Weight", description: "During this 2 mi jog starting at W 32nd, going up to W 52nd, and back on 7th Avenue, you will see why tourists come from around the world to visit the Big Apple. \n\nDon't be afraid to venture down a side street! You may also discover Broadway, Rockefellar Center, Madame Tussauds and more!", fitness_level: 2)
Tactic.create(action: "Cardio: Jog or swim at Rockaway Beach", goal: "Lose Weight", description: "Escape the concrete jungle by stopping by this local beach in Queens! \n\nDepending on the season, you can swim continously for 45 minutes or stay dry and jog along the water's edge for at least 3 miles (Rockaway is 5.5 mi in length total).", fitness_level: 2)
Tactic.create(action: "Cardio: Jog there and back through Brooklyn Bridge Park", goal: "Lose Weight", description: "Located in DUMBO, this walk offers 1.3 mi (X2) of waterfront with increible views of FiDi. \n\nPrepare for lots of pictures.", fitness_level: 2)
Tactic.create(action: "Cardio: Jog around Battery Park", goal: "Lose Weight", description: "Jog down and back along the waterfront (2 mi in total). \n\nPrepare for amazing views of downtown (including the Freedom Tower) as well as the Statue of Liberty!", fitness_level: 2)
Tactic.create(action: "Cardio: Jog through Soho", goal: "Lose Weight", description: "Jog for at least 3 mi and have fun exploring! \n\nSoho is known for its quaint cobblestone roads that are full of designer boutiques, galleries, and restaurants. \n\nYou could easily spend all day in this neighborhood. Be careful to not twist your ankle on those old streets!", fitness_level: 2)
Tactic.create(action: "Cardio: Bike through Greenpoint & Long Island City", goal: "Lose Weight", description: "Bike for at least 7 mi and have fun exploring! \n\nLong Island City is at the tip of Queens, offers an amazing view of Midtown, and has more dogs than your heart could ever desire!" , fitness_level: 2)

#Lose weight, level 3
Tactic.create(action: "Cardio: Run around the Central Park Resevoir three times", goal: "Lose Weight", description: "This man-made lake is one of the park's most iconic routes; many celebrities have been spotted jogging here. \n\nThis path is 1.58 mi (X3) in length and offers stunning views of the Upper West Side skyline.", fitness_level: 3)
Tactic.create(action: "Cardio: Run the High Line three times", goal: "Lose Weight", description: "This 1.45 mi (X3) long elevated greenway was converted from an old railway. \n\nOn this path, you will wind through soaring buildings and stand above traffic in Chelsea.", fitness_level: 3)
Tactic.create(action: "Cardio: Run there and back over the Brooklyn Bridge twice", goal: "Lose Weight", description: "Undoubtedly the most famous bridge in all of NYC - the 4 mi path will provide a steep incline to work out those leg muscles!", fitness_level: 3)
Tactic.create(action: "Cardio: Run up and down Fifth Avenue twice", goal: "Lose Weight", description: "Run there and back twice starting at E 40th, going up to E 60th. \n\nDuring this 6 mi run, you will see Bryant Park and the countless stores that make the street so famous. I hope you brought your credit card! Although, window shopping is just fine - the store front displays are a sight to see in themselves.", fitness_level: 3)
Tactic.create(action: "Cardio: Run there and back through Times Square twice" , goal: "Lose Weight", description: "Run there and back twice starting at W 32nd, going up to W 52nd on 7th Avenue. \n\nDuring this 4 mi run, you will see why tourists come from around the world to visit the Big Apple. Don't be afraid to venture down a side street! You may also discover Broadway, Rockefellar Center, Madame Tussauds and more!", fitness_level: 3)
Tactic.create(action: "Cardio: Run or swim at Rockaway Beach", goal: "Lose Weight", description: "Escape the concrete jungle by stopping by this local beach in Queens! \n\nDepending on the season, you can swim continously for 60 minutes or stay dry and jog along the water's edge for at least 4 miles (Rockaway is 5.5 mi in length total).", fitness_level: 3)
Tactic.create(action: "Cardio: Run there and back through Brooklyn Bridge Park twice", goal: "Lose Weight", description: "Located in DUMBO, this walk offers 1.3 mi (X4) of waterfront with increible views of FiDi. \n\nPrepare for lots of pictures.", fitness_level: 3)
Tactic.create(action: "Cardio: Run around Battery Park", goal: "Lose Weight", description: "Run down and back along the waterfront twice (4 mi in total). \n\nPrepare for amazing views of downtown (including the Freedom Tower) as well as the Statue of Liberty!", fitness_level: 3)
Tactic.create(action: "Cardio: Run through Soho & Tribeca", goal: "Lose Weight", description: "Run for at least 4 mi and have fun exploring! \n\nSoho is known for its quaint cobblestone roads that are full of designer boutiques, galleries, and restaurants. You could easily spend all day in this neighborhood. \n\nBe careful to not twist your ankle on those old streets! Extend your run into Tribeca; a popular location for filming movies and TV shows.", fitness_level: 3)
Tactic.create(action: "Cardio: Bike through Greenpoint, Long Island City, & Manhattan", goal: "Lose Weight", description: "Bike for at least 10 mi and have fun exploring! \n\nLong Island City is at the tip of Queens, offers an amazing view of Midtown, and has more dogs than your heart could ever desire!" , fitness_level: 3)

#Lose weight, meals
Tactic.create(action: "Snack: Low fat vanilla yogurt with berries", goal: "Lose Weight", description: "Yogurt is a source of protein which will keep you feeling satisified when combined with the fiber in berries.")
Tactic.create(action: "Snack: Apple slices with peanut butter", goal: "Lose Weight", description: "This classic pairing combines fiber and protein for an easy and filling on-the-go snack." )
Tactic.create(action: "Snack: Popcorn", goal: "Lose Weight", description: "Perfect for satisfying crunchy cravings. \n\nWe recommend Angie's Boom Chicka pop Sea Salt popcorn. It's whole grain and a good source of antioxidants that aid in repairing cell damage.")
Tactic.create(action: "Snack: Celery and hummus", goal: "Lose Weight", description: "Hummus is a great source of plant-based protein and, as a result, helps to fight inflammation and aids in healthy digestion." )
Tactic.create(action: "Breakfast: Egg fritatta with veggies", goal: "Lose Weight", description: "Stir up some eggs and add in any veggies you have in the fridge. \n\nBake and enjoy a protein-packed breakfast. This should keep you full until lunch!")
Tactic.create(action: "Breakfast: Overnight oats with banana", goal: "Lose Weight", description: "Throw oats, milk, banana, and any other toppings of your choice into a jar and refrigerate overnight for a simple and easy breakfast. Staying on track with your meal plan starts with the prep.")
Tactic.create(action: "Lunch: Smoothie", goal: "Lose Weight", description: "Mix favorite fruit, a low fat yogurt, and water. \n\nTo kick it up a notch, add in spinach! It will turn your drink green, but don't let that startle you - you won't be able to taste it. Spinach offers protection from cancer, aids in bone growth, and improves our overall cardiovascular health.")
Tactic.create(action: "Lunch: Salad from Sweetgreen", goal: "Lose Weight", description: "You can find this salad chain throughout the city - try one of their signature bowls or create your own!")
Tactic.create(action: "Dinner: Salmon with brussel sprouts & couscous" , goal: "Lose Weight", description: "For added flavor, mix soy sauce, honey, sesame oil, garlic, and sirarcha together. \n\nBefore taking the salmon off the pan, baste some of this mixture in.")
Tactic.create(action: "Dinner: Chicken and brown rice", goal: "Lose Weight", description: "A staple that doesn't get much easier! Add a veggie side of your choosing.")

#Build muscle, level 1
Tactic.create(action: "Strength - Core: Hold a plank for 60 seconds", goal: "Build Muscle", description: "1. Get down on all fours with your palms and knees planted on your mat (your arms should be fully extended to keep your body raised; your palms should be slightly wider than shoulder width), \n\n2. Extend your legs and dig your toes into the ground (squeeze your abs and glutes for stablization; your butt should stay in line with your body - do not push it up or let your hips hang), \n\n3. Make sure your neck is neutral by extending your head to align with and lengthen your spine, \n\n4. Hold position for at least 60 seconds.", fitness_level: 1)
Tactic.create(action: "Strength - Core: 50 scissor kicks", goal: "Build Muscle", description: "1. Lie on your back on your mat with your legs extended out in front of you, \n\n2. Place your arms by your sides with your palms facing down (you can also place your hands under your glutes below the small of your back if that's easier), \n\n3. Kick your legs up and down in an alternate pattern 50 times (this move gets it's name from the way in which your legs look when one kicks up and the other stays down), \n\n4. Press your palms into the floor for stablilization, \n\n5. Engage your core by pressing your lower back into the mat and tucking your pelvis. \n\n*NOTE: 1 kick = both legs having gone in the air once.*", fitness_level: 1)
Tactic.create(action: "Strength - Core: 50 mountain climbers", goal: "Build Muscle", description: "1. Get into a plank position (see our recommended plank activity if you need to know how), \n\n2. Tuck one leg at a time, driving your knee up to your chest 50 times (avoid lifting your hips - stablize your body for optimal muscle stimulation). \n\n*NOTE: 1 'climb' = both legs have been driven to your chest once.*", fitness_level: 1)
Tactic.create(action: "Strength - Core: 50 russian twists", goal: "Build Muscle", description: "1. Take a seated position on your mat, \n\n2. Bend your knees and raise your legs off of the ground, \n\n3. Link your hands together in front of your chest, \n\n4. Rotate your arms all the way over to one side, then do the same in the other direction. Count that as one rep and aim for 50 in total.", fitness_level: 1)
Tactic.create(action: "Strength - Arms: Overhead press 20 pounds (or two 10 pound dumbbells) x 20 times", goal: "Build Muscle", description: "1. Stand with your feet shoulder level apart, \n\n2. Hold your weights in front of and just above your shoulders with your palms facing it & knuckles up to the sky, \n\n3. In one fluid motion, press the weights straight up over your head, turning your palms out - with the back of your hands facing your body, \n\n4. Keep your elbows soft and fully extend your arms, \n\n5. Bring the weights back down to the beginning shoulder position and start again. Be sure to engage your legs, core, and glutes for stablization. Do this 20 times.", fitness_level: 1)
Tactic.create(action: "Strength - Arms: 20 push ups", goal: "Build Muscle", description: "1. Get down on all fours with your palms and knees planted on your mat (your arms should be fully extended; your palms should be slightly wider than shoulder width), \n\n2. Extend your legs and dig your toes into the ground (squeeze your abs and glutes for stablization; your butt should stay in line with your body - do not push it up or let your hips hang), \n\n3. Make sure your neck is neutral by extending your head to align with and lengthen your spine, \n\n4. Bend your arms at the elbow and lower your chest almost to the ground (or as far as you can go), \n\n5. Press your arms back up to the beginning fully extended position and start again. Do this 20 times.", fitness_level: 1)
Tactic.create(action: "Strength - Arms: 20 bicep curls w/ 20 pounds (or two 10 pounds dumbbells)", goal: "Build Muscle", description: "1. Hold weights with your arms down in front of you and by your side (your palms should be facing out), \n\n2. Bend your arms and bring the weights straight up - until they are in line with your shoulders - repeat this process 20 times.", fitness_level: 1)
Tactic.create(action: "Strength - Legs: 50 suitcase dead lifts", goal: "Build Muscle", description: "1. Start standing with feet shoulders width apart with a 20 lb kettlebell on the ground next to your right foot, \n\n2. Bend your knees, hinge at the waist, and grip the kettlebell with your right hand (make sure your back remains straight; there should be a slight bend in your knees but this is not a squat), \n\n3. Pick the kettlebell off of the ground and stand up, \n\n4. Transfer the kettlebell to your left hand, bend your knees, hinge at the waist, set the kettlebell on the floor next to your left foot, and stand tall, \n\n5. Repeat this process 50 times (doing 25 on each side).", fitness_level: 1)
Tactic.create(action: "Strength - Legs: 50 goblin squats", goal: "Build Muscle", description: "1. Hold a 20 lb kettlebell against and in the middle of your chest (arms should be bent upwards), \n\n2. Squat fully with your elbows coming in between your knees (do not drop your chest and hold the original position; your legs should be at a 90 degree angle or parallel with the floor), \n\n3. Drive through your heels and stand tall. Repeat this 50 times.", fitness_level: 1)
Tactic.create(action: "Strength - Legs: 50 lateral lunges", goal: "Build Muscle", description: "1. Start in a standing position with your feet shoulder width apart; you should hold a 20 lb kettlebell against and in the middle of your chest (arms should be bent upwards), \n\n2. Step out to the side with your right leg, bending into a side squat, \n\n3. Step back to center and repeat on the left side - alternating back and forth 50 times (25 on each side).", fitness_level: 1)


#Build muscle, level 2
Tactic.create(action: "Strength - Core: Hold a plank for 90 seconds", goal: "Build Muscle", description: "1. Get down on all fours with your palms and knees planted on your mat (your arms should be fully extended to keep your body raised; your palms should be slightly wider than shoulder width), \n\n2. Extend your legs and dig your toes into the ground (squeeze your abs and glutes for stablization; your butt should stay in line with your body - do not push it up or let your hips hang), \n\n3. Make sure your neck is neutral by extending your head to align with and lengthen your spine, \n\n4. Hold position for at least 90 seconds.", fitness_level: 2)
Tactic.create(action: "Strength - Core: 75 scissor kicks", goal: "Build Muscle", description: "1. Lie on your back on your mat with your legs extended out in front of you, \n\n2. Place your arms by your sides with your palms facing down (you can also place your hands under your glutes below the small of your back if that's easier), \n\n3. Kick your legs up and down in an alternate pattern 75 times (this move gets it's name from the way in which your legs look when one kicks up and the other stays down), \n\n4. Press your palms into the floor for stablilization, \n\n5. Engage your core by pressing your lower back into the mat and tucking your pelvis. \n\n*NOTE: 1 kick = both legs having gone in the air once.*", fitness_level: 2)
Tactic.create(action: "Strength - Core: 75 mountain climbers", goal: "Build Muscle", description: "1. Get into a plank position (see our recommended plank activity if you need to know how), \n\n2. Tuck one leg at a time, driving your knee up to your chest 75 times (avoid lifting your hips - stablize your body for optimal muscle stimulation). \n\n*NOTE: 1 'climb' = both legs have been driven to your chest once.*", fitness_level: 2)
Tactic.create(action: "Strength - Core: 75 russian twists", goal: "Build Muscle", description: "1. Take a seated position on your mat, \n\n2. Bend your knees and raise your legs off of the ground, \n\n3. Link your hands together in front of your chest, \n\n4. Rotate your arms all the way over to one side, then do the same in the other direction. Count that as one rep and aim for 75 in total.", fitness_level: 2)
Tactic.create(action: "Strength - Arms: Overhead press 30 pounds (or two 15 pound dumbbells) x 20 times", goal: "Build Muscle", description: "1. Stand with your feet shoulder level apart, \n\n2. Hold your weights in front of and just above your shoulders with your palms facing it & knuckles up to the sky, \n\n3. In one fluid motion, press the weights straight up over your head, turning your palms out - with the back of your hands facing your body, \n\n4. Keep your elbows soft and fully extend your arms, \n\n5. Bring the weights back down to the beginning shoulder position and start again. Be sure to engage your legs, core, and glutes for stablization. Do this 20 times.", fitness_level: 2)
Tactic.create(action: "Strength - Arms: 50 push ups", goal: "Build Muscle", description: "1. Get down on all fours with your palms and knees planted on your mat (your arms should be fully extended; your palms should be slightly wider than shoulder width), \n\n2. Extend your legs and dig your toes into the ground (squeeze your abs and glutes for stablization; your butt should stay in line with your body - do not push it up or let your hips hang), \n\n3. Make sure your neck is neutral by extending your head to align with and lengthen your spine, \n\n4. Bend your arms at the elbow and lower your chest almost to the ground (or as far as you can go), \n\n5. Press your arms back up to the beginning fully extended position and start again. Do this 50 times.", fitness_level: 2)
Tactic.create(action: "Strength - Arms: 30 bicep curls w/ 15 pounds (or two 15 pounds dumbbells)", goal: "Build Muscle", description: "1. Hold weights with your arms down in front of you and by your side (your palms should be facing out), \n\n2. Bend your arms and bring the weights straight up - until they're in line with your shoulders - repeat this process 20 times.", fitness_level: 2)
Tactic.create(action: "Strength - Legs: 70 suitcase dead lifts", goal: "Build Muscle", description: "1. Start standing with feet shoulders width apart with a 20 lb kettlebell on the ground next to your right foot, \n\n2. Bend your knees, hinge at the waist, and grip the kettlebell with your right hand (make sure your back remains straight; there should be a slight bend in your knees but this is not a squat), \n\n3. Pick the kettlebell off of the ground and stand up, \n\n4. Transfer the kettlebell to your left hand, bend your knees, hinge at the waist, set the kettlebell on the floor next to your left foot, and stand tall, \n\n5. Repeat this process 70 times (doing 35 on each side).", fitness_level: 2)
Tactic.create(action: "Strength - Legs: 70 goblin squats", goal: "Build Muscle", description: "1. Hold a 20 lb kettlebell against and in the middle of your chest (arms should be bent upwards), \n\n2. Squat fully with your elbows coming in between your knees (do not drop your chest and hold the original position; your legs should be at a 90 degree angle or parallel with the floor), \n\n3. Drive through your heels and stand tall. Repeat this 70 times.", fitness_level: 2)
Tactic.create(action: "Strength - Legs: 70 lateral lunges", goal: "Build Muscle", description: "1. Start in a standing position with your feet shoulder width apart; you should hold a 20 lb kettlebell against and in the middle of your chest (arms should be bent upwards), \n\n2. Step out to the side with your right leg, bending into a side squat, \n\n3. Step back to center and repeat on the left side - alternating back and forth 70 times (35 on each side).", fitness_level: 2)

#Build muscle, level 3
Tactic.create(action: "Strength - Core: Hold a plank for 120 seconds", goal: "Build Muscle", description: "1. Get down on all fours with your palms and knees planted on your mat (your arms should be fully extended to keep your body raised; your palms should be slightly wider than shoulder width), \n\n2. Extend your legs and dig your toes into the ground (squeeze your abs and glutes for stablization; your butt should stay in line with your body - do not push it up or let your hips hang), \n\n3. Make sure your neck is neutral by extending your head to align with and lengthen your spine, \n\n4. Hold position for at least 120 seconds.", fitness_level: 3)
Tactic.create(action: "Strength - Core: 100 scissor kicks", goal: "Build Muscle", description: "1. Lie on your back on your mat with your legs extended out in front of you, \n\n2. Place your arms by your sides with your palms facing down (you can also place your hands under your glutes below the small of your back if that's easier), \n\n3. Kick your legs up and down in an alternate pattern 100 times (this move gets it's name from the way in which your legs look when one kicks up and the other stays down), \n\n4. Press your palms into the floor for stablilization, \n\n5. Engage your core by pressing your lower back into the mat and tucking your pelvis. \n\n*NOTE: 1 kick = both legs having gone in the air once.*", fitness_level: 3)
Tactic.create(action: "Strength - Core: 100 mountain climbers", goal: "Build Muscle", description: "1. Get into a plank position (see our recommended plank activity if you need to know how), \n\n2. Tuck one leg at a time, driving your knee up to your chest 100 times (avoid lifting your hips - stablize your body for optimal muscle stimulation). \n\n*NOTE: 1 'climb' = both legs have been driven to your chest once.*", fitness_level: 3)
Tactic.create(action: "Strength - Core: 100 russian twists", goal: "Build Muscle", description: "1. Take a seated position on your mat,\n\n2. Bend your knees and raise your legs off of the ground, \n\n3. Link your hands together in front of your chest, \n\n4. Rotate your arms all the way over to one side, then do the same in the other direction. Count that as one rep and aim for 100 in total.", fitness_level: 3)
Tactic.create(action: "Strength - Arms: Overhead press 50 pounds (or two 25 pound dumbbells) x 20 times", goal: "Build Muscle", description: "1. Stand with your feet shoulder level apart, \n\n2. Hold your weights in front of and just above your shoulders with your palms facing it & knuckles up to the sky, \n\n3. In one fluid motion, press the weights straight up over your head, turning your palms out - with the back of your hands facing your body, \n\n4. Keep your elbows soft and fully extend your arms, \n\n5. Bring the weights back down to the beginning shoulder position and start again. Be sure to engage your legs, core, and glutes for stablization. Do this 20 times.", fitness_level: 3)
Tactic.create(action: "Strength - Arms: 70 push ups", goal: "Build Muscle", description: "1. Get down on all fours with your palms and knees planted on your mat (your arms should be fully extended; your palms should be slightly wider than shoulder width), \n\n2. Extend your legs and dig your toes into the ground (squeeze your abs and glutes for stablization; your butt should stay in line with your body - do not push it up or let your hips hang), \n\n3. Make sure your neck is neutral by extending your head to align with and lengthen your spine, \n\n4. Bend your arms at the elbow and lower your chest almost to the ground (or as far as you can go), \n\n5. Press your arms back up to the beginning fully extended position and start again. Do this 70 times.", fitness_level: 3)
Tactic.create(action: "Strength - Arms: 40 bicep curls w/ 50 pounds (or two 25 pounds dumbbells)", goal: "Build Muscle", description: "1. Hold weights with your arms down in front of you and by your side (your palms should be facing out), \n\n2. Bend your arms and bring the weights straight up - until they're in line with your shoulders - repeat this process 20 times.", fitness_level: 3)
Tactic.create(action: "Strength - Legs: 100 suitcase dead lifts", goal: "Build Muscle", description: "1. Start standing with feet shoulders width apart with a 20 lb kettlebell on the ground next to your right foot, \n\n2. Bend your knees, hinge at the waist, and grip the kettlebell with your right hand (make sure your back remains straight; there should be a slight bend in your knees but this is not a squat), \n\n3. Pick the kettlebell off of the ground and stand up, \n\n4. Transfer the kettlebell to your left hand, bend your knees, hinge at the waist, set the kettlebell on the floor next to your left foot, and stand tall, \n\n5. Repeat this process 100 times (doing 50 on each side).", fitness_level: 3)
Tactic.create(action: "Strength - Legs: 100 goblin squats", goal: "Build Muscle", description: "1. Hold a 20 lb kettlebell against and in the middle of your chest (arms should be bent upwards), \n\n2. Squat fully with your elbows coming in between your knees (do not drop your chest and hold the original position; your legs should be at a 90 degree angle or parallel with the floor), \n\n3. Drive through your heels and stand tall. Repeat this 100 times.", fitness_level: 3)
Tactic.create(action: "Strength - Legs: 100 lateral lunges", goal: "Build Muscle", description: "1. Start in a standing position with your feet shoulder width apart; you should hold a 20 lb kettlebell against and in the middle of your chest (arms should be bent upwards), \n\n2. Step out to the side with your right leg, bending into a side squat, \n\n3. Step back to center and repeat on the left side - alternating back and forth 100 times (50 on each side).", fitness_level: 3)

#Build muscle, meals
Tactic.create(action: "Snack: Protein shake", goal: "Build Muscle", description: "Shakes that contain Whey protein are recommended. \n\nWhey protein promotes muscle gain and improves performance and recovery.")
Tactic.create(action: "Snack: Greek yogurt and mixed berries", goal: "Build Muscle", description: "Greek yogurt often contains ~ double the amount of protein as regular yogurt and contributes to growing lean mass." )
Tactic.create(action: "Snack: Lean jerky", goal: "Build Muscle", description: "Most of the fat is removed from lean jerky during processing, so almost all of the calories in this snack come directly from protein; resulting in stimulated muscle growth.")
Tactic.create(action: "Snack: Low fat cottage cheese", goal: "Build Muscle", description:"Cottage cheese is packed with protein and gives a hearty dose of the important muscle-building amino acid - leucine." )
Tactic.create(action: "Breakfast: Eggs and turkey sausage", goal: "Build Muscle", description: "This selection contains high quality protein. \n\nAdditionally, eggs contain healthy fats and other important nutrients like vitamin B and choline and are thus critically important for energy production (i.e., making each workout session more meaningful).")
Tactic.create(action: "Breakfast: Whole wheat bread and crunchy peanut butter", goal: "Build Muscle", description: "This meal offers a strong mix of carbohydrates and fat and is a good way to intake the extra calories needed to build muscle. If you go over your desired caloric intake, don't worry - the energy provided from this meal will lead you to exceed your workout goals; allowing you to exercise harder for longer.")
Tactic.create(action: "Lunch: Chicken and quinoa", goal: "Build Muscle", description: "This meal is rich in protein. Quinoa also provides complex carbohydrates which will leave you feeling full for longer.")
Tactic.create(action: "Lunch: Tuna sandwich", goal: "Build Muscle", description: "Tuna provides high quantities of omega-3 fatty acids that support overall muscle health. And it's so simple to make!")
Tactic.create(action: "Dinner: Lean beef and veggie of choice", goal: "Build Muscle", description: "Lean beef supports muscle gain without providing too many extra calories. \n\nBrown rice is loaded with the carbohydrates necessary power your physical activity and allow for greater stimulus of your muscles.")
Tactic.create(action: "Dinner: Scallops, brown rice, and edamame", goal: "Build Muscle", description: "Scallops provide a lot of protein with very little fat; allowing for the addition of lean muscle without the extra bulk. \n\nEdamame is the term for immature soybeans. Soybeans are a great source of iron. Iron is used to store and transport oxygen in your blood and muscles.")



