require 'tty-box'
require 'colorize'

class Gif
    def self.frame_one
        puts "
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmdhmmmdhhdMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhoyhhhddhyhNMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNsoohddhhyyshMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMdssmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhooshhhhyysssMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMN+:/+yNMMMMmyoy/dmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMhsyydhhhhysysNMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMNho-.:yMMMs:/oodmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMNhdmmmmddhyysdMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMNh:-oMN+///sdddNNNMMMMMMMMMMMMMMMMMMhdmNNNNmmmNmmmNmdhyhhyNMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMN:--+NhoooyhdmNNNMMMMMMMMMMMMMMMMMMh++oyssssddyddddddhdhhhNMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMNm+---:+oooso+yNMMMMMMMMMMMMMMMMMMMMyyyso+ssydssyyyhhddhyhyyNMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMNs/:/::----:+/::::/odMMMMMMMMMMMMMMMMMMMMdyhsosyhyyyssyhdhyssssyMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMmso::///::----::-:::/sMMMMMMMMMMMMMMMMMMMmhshhysosssssysyyssossoyMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMd++oo+o++///////////++mMMMMMMMMMMMMMMMMMMNhhyhyyhyyssyysssooosyssNMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMs/:+ooo++//++ooooo+o+sMMMMMMMMMMMMMMMMMMMmhdhdhyhhhyysyyysoosssdMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMM+///+o+///////++++++sNMMMMMMMMMMMMMMMMMMNdddhddddhhhhyhyhyyhdNNMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMM+//++so///::://///++mMMMMMMMMMMMMMMMMmddyyhhdddddddmddhyhmNMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMdssymN+///:://////+sMMMMMMMMMMMMMMMMhyysodmhhhhhdddddddhMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMN+//////////++yMMMMMMMMMMMMMMMMMmdhhmdhyhyhhhhhysymMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMo///////////+yMMMMMMMMMMMMMMMMMMMmhddhhhhhyyhhyyydMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMN/////////////oMMMMMMMMMMMMMMMMMMMmyhdhhyyyhyyyyysyhMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMN+//////////////hMMMMMMMMMMMMMMMMMMyyyhdmddhhhhhyysooMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMy///////////////oMMMMMMMMMMMMMMMMMmyyyhhhdddhyyyyssssMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMN///::/::////////+NMMMMMMMMMMMMMMMMdyyyhhhdhyhhhhhysssMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMo::::////////::///hMMMMMMMMMMMMMMMMhyyyyyhdmhyyyyysssyMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMy::::///////:::////oMMMMMMMMMMMMMMMMyyyyyyhdNdhhyyysssdMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMm:::///++s+/////////hMMMMMMMMMMMMMMMNyysssyhNMNhhhhyyssNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMM+:::///++yy/////////mMMMMMMMMMMMMMMMdyysssyNMMMmhhhyysyMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMd:::///++sNN++///////NMMMMMMMMMMMMMMMhyyssymMMMMNdhhyyydMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMo::///++sNMMh+//////+MMMMMMMMMMMMMMMNyyyyyhMMMMMMddhyyymMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMm/:///+++NMMMNo+///+++NMMMMMMMMMMMMMMmhhhhyhMMMMMMmdhhysdMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMy///++++hMMMMMy+++++oodMMMMMMMMMMMMMNdddhdmNMMMMMMmdhhyysNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMs/++++odMMMMMMs+++++++mMMMMMMMMMMMMNddddhhNMMMMMMMddddhyymMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMm+/+ooomMMMMMMMd+++++oomMMMMMMMMMMMMMdmddhdMMMMMMMMmmdddhhMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMh+++oosMMMMMMMMMs+++ooomMMMMMMMMMMMMMmddddmMMMMMMMMNmmdddhMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMh+++oodMMMMMMMMMho+ooooNMMMMMMMMMMMMMmdddmMMMMMMMMMMNmhdmhNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMy+++osMMMMMMMMMMmo+oooomMMMMMMMMMMMMMmddmMMMMMMMMMMMNmhdmdNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMs++oodMMMMMMMMMMNsooosomMMMMMMMMMMMMNddmMMMMMMMMMMMMMmdhddMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMo++osMMMMMMMMMMMMsooooomMMMMMMMMMMMMNyydNMMMMMMMMMMMMmdhdmMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMo++osMMMMMMMMMMMMo++//+NMMMMMMMMMMMMs--/sMMMMMMMMMMMMmmhhdMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMy++++NMMMMMMMMMMMho::::NMMMMMMMMMMMh.../dMMMMMMMMMMMMmmhs:mMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMNs-:/+sNMMMMMMMMMMMMy...-MMMMMMMMMMMN-.+.oMMMMMMMMMMMMMMy+..:mMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMM/...:NMMMMMMMMMMMMMMhoosdMMMMMMMMMMMN-++.oMMMMMMMMMMMMMMh-++++MMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMyo+smMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhhMMMMMMMMMMMMMMMNyssohMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        ".colorize(:magenta)
        sleep (0.09)
        system 'clear'
    end

    def self.frame_two
        puts "
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmddmNmdhdNMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMyshhdddhhymMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmyoshdddhyysmMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNyshNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMyooshhhhyyysyMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNs+o/dmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMssyyhhhhhysysmMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMmNMMMMMmo//y+dmNNMMMMMMMMMMMMMMMMMMMMMNyMMMMMdyhddddddhyyshMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMhs+:::::omMh++//+dmmNNMMMMMMMMMMMMMMMMMMMMd+ohNMMNNmmmmmmmhhhhsmMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMyyhhdhho--odo+oosdmNNNNMMMMMMMMMMMMMMMMMMNysoooyyyddhdmddddhdhhyNMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMmy:---/+++osomNMMMMMMMMMMMMMMMMMMMMdddhysosyhosyhhhhddhhhyyMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMd+/:::-----://::/omMMMMMMMMMMMMMMMMMMMNdssyssyhsyysyyddhyssyshMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMNy////oo/::----::::/hMMMMMMMMMMMMMMMMMMMdhsydyyyyyyysyyyysssssssMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMys++++/+so+/::////++oNMMMMMMMMMMMMMMMMMMhhhyhdshhyssyyssoososyyodMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMy:/:++o//++//++oooooodMMMMMMMMMMMMMMMMMMmyhdhdddhhhyysysso+osyssdMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMm/+//+++/////+/+++oo+yMMMMMMMMMMMMMMMMMMMddddddddmdhhhyyhysssyhdNMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMh///++s+/////::////++mMMMMMMMMMMMMMMMMmdysydhhddddddddhhyydNNNMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMmoooymNo///::://///+sMMMMMMMMMMMMMMMMNhhyoymhhhhhdddmmmdhNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMNNMMN+///////////+yMMMMMMMMMMMMMMMMMMNdhmmhhyyyhddhyyhmMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMN////:///////+yMMMMMMMMMMMMMMMMMMMmhhhhhhhhyhhhyssNMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMN////:////////oMMMMMMMMMMMMMMMMMMMdhddhhhhhyyhyyyyhmMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMNo//////////////yMMMMMMMMMMMMMMMMMMyyyhdddhhhhyyyysoyMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMy///////////////+MMMMMMMMMMMMMMMMMmsyyyhdmddhyyyysssyMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMM///:::::::///////mMMMMMMMMMMMMMMMMdyyyhhhddhhhhhhyssyMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMy:::://///////:///yMMMMMMMMMMMMMMMMhyyyyyhdmhyyyyyssshMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMd:::::://///:::////+MMMMMMMMMMMMMMMMhyyysyhdNdhhyyysssdMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMN/::://++oo/////////+MMMMMMMMMMMMMMMNyyyssyhNMNhhhhyyssNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMy:::////+od+////////oMMMMMMMMMMMMMMMdsysssyNMMMmhhhyyshMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMN/:::///++dMs+///////+MMMMMMMMMMMMMMMhyysssdMMMMNdhhyyydMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMh:::///++hMMm+///////+NMMMMMMMMMMMMMmyyyyyyMMMMMMddhyysNMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMo:///+++sMMMMo+/////++mMMMMMMMMMMMMMdhhhhyyMMMMMMmhhhysNMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMh////++++mMMMMy++/+++oomMMMMMMMMMMMMNdddhmmNMMMMMMmdhhyshMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMs//+++osmMMMMMh+++++++oMMMMMMMMMMMMNddmdhhNMMMMMMMdddhyysmMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMh//+oooyMMMMMMMmo+++++ooMMMMMMMMMMMMMmmmdhhNMMMMMMNmmdddhhMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMo/++oosNMMMMMMMMy++++oosMMMMMMMMMMMMMmmmdhmMMMMMMMMNmmdmdhMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMo++ossdMMMMMMMMMmo++oooyMMMMMMMMMMMMMNmdddMMMMMMMMMMNmhdmhNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMM+++osyMMMMMMMMMMMso+oooyMMMMMMMMMMMMMNmddNMMMMMMMMMMNmhdmdMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMm++osyNMMMMMMMMMMMhooosohMMMMMMMMMMMMMNddNMMMMMMMMMMMMmhhddMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMd++osNMMMMMMMMMMMMdoooosdMMMMMMMMMMMMmoyhmMMMMMMMMMMMMmdhdmMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMh++osMMMMMMMMMMMMMm+++/+NMMMMMMMMMMMM+:::sMMMMMMMMMMMMmdyhmMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMd++osMMMMMMMMMMMMMNo//::NMMMMMMMMMMMd-../mMMMMMMMMMMMMmdh+-mMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMd::/+hMMMMMMMMMMMMMMh...-MMMMMMMMMMMM/+++/MMMMMMMMMMMMMNy/+.-mMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMd...-yMMMMMMMMMMMMMMMhoosdMMMMMMMMMMMMs.../MMMMMMMMMMMMMMh-++++MMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMNyooyMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmMMMMMMMMMMMMMMMNyooohMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        ".colorize(:magenta)
        sleep (0.09)
        system 'clear'
    end

    def self.frame_three
        puts "
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmmNNmddNMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNyydddddhydMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhooyhddhhyyhMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNyoymNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmoooyhhhhyyysmMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh:/+smNMMMMMMMMMMMMMMMMMMMMMMMMMMNMMdosyhhhhhyyyysNMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs/:+osmNNMMMMMMMMMMMMMMMMMMMMMMMMm/hMNyyhdddhdhhyyshMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmo++//odmNNMMMMMMMMMMMMMMMMMMMMMMMy++sNMNmddmmmdhyyysmMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMNds+/+hms++oosmmmNMMMMMMMMMMMMMMMMMMMMMNdsyyosydhhdmmdhhhhhyyMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMh+////:-::/++++osdNMMMMMMMMMMMMMMMMMMMNhhhhyysosyoshhhhhdhdhhyhMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMo///::::::---::::::/oMMMMMMMMMMMMMMMMMMNMmhssssssyoyyyyydddyyhhsNMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMmo::///+o+/:------::/mMMMMMMMMMMMMMMMMMMmdysyhyyysyyysyyhhyyssssyMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMd///+///+oo+/:::://+hMMMMMMMMMMMMMMMMMMdyhyyydhyhyssyysssssssysoyMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMy::://+//+++++//++oosMMMMMMMMMMMMMMMMMMmyyhhhhhddhhysyysooossyssomMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMs:////++///+/+//+oooomMMMMMMMMMMMMMMMMMmhshmdddhdddhhhyyhyoossoshmMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMM/:///+o+//////:////++MMMMMMMMMMMMMMMMMNyyysmdddddmmdddhyyydNmmmNMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMyo+oymd+////:://///+yMMMMMMMMMMMMMMMMMMmhhhmdmdddddmmmmhhNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMNNNMMd+///////////+hMMMMMMMMMMMMMMMMMMMmmmmhdhyyhddhhhhNMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMh////////////+yMMMMMMMMMMMMMMMMMMMhhhhyyyyhhhhhyssMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMd/////////////oMMMMMMMMMMMMMMMMMMMmhdhhhhhhhhhhhyyhNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMN+//////////////yMMMMMMMMMMMMMMMMMMyhhhddhhhhhyyyysohMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMy///////////////+MMMMMMMMMMMMMMMMMmsyyyhdmddhhyyyyssyMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMN////://::/://////NMMMMMMMMMMMMMMMMhyyyyhhddhhhhhhyssyMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMh/:///////////:///yMMMMMMMMMMMMMMMMhsyyyyhddhyyhyyyssyMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMN/::::///////::////+MMMMMMMMMMMMMMMMhsyysyyhmddhhyyssshMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMs:::///++s+/////////mMMMMMMMMMMMMMMMyysssyymMmhhhhyyssNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMm/::///+++dy/////////hMMMMMMMMMMMMMMdsyssssmMMMmhhhyysyMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMs:::///++hMm+////////yMMMMMMMMMMMMMMhyyssshMMMMMdhhhyyhMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMM/:////++yMMMy+///////sMMMMMMMMMMMMMmyyysyyNMMMMMmdhyyydMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMh/////+++NMMMm+///++/++NMMMMMMMMMMMMdhhhhyyMMMMMMmdhhysmMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMm+///+++odMMMMMo+++++++oNMMMMMMMMMMMmhddhmdmMMMMMMNdhhyyhMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMNy++/++osdMMMMMMo+++++++sMMMMMMMMMMMmddmdhdNMMMMMMMmddhhyymMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMy++/+oosNMMMMMMMy++++++oyMMMMMMMMMMMNmmmdhdNMMMMMMMmmmddhyNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMM+//++osmMMMMMMMMmo++++oodMMMMMMMMMMMMmmmddmMMMMMMMMNmmdddhNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMN+//+osdMMMMMMMMMMso++ooomMMMMMMMMMMMMmmmddNMMMMMMMMMNmddmhNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMm+/+oshMMMMMMMMMMMdo++oooMMMMMMMMMMMMMNmddmMMMMMMMMMMNmhdmdNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMm++oshMMMMMMMMMMMMNsooosyMMMMMMMMMMMMMmmddNMMMMMMMMMMMmdhddMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMh+osyMMMMMMMMMMMMMMsoooohMMMMMMMMMMMMs+ydmNMMMMMMMMMMMmdhdmMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMs+osmMMMMMMMMMMMMMMy++++NMMMMMMMMMMMh--+oNMMMMMMMMMMMMmdyhmMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMN++ohMMMMMMMMMMMMMMMh//::NMMMMMMMMMMM/..:hMMMMMMMMMMMMNmdy+-dMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMN+::/dMMMMMMMMMMMMMMMh--.-NMMMMMMMMMMd.++.yMMMMMMMMMMMMMNy/+.-mMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMo...-MMMMMMMMMMMMMMMMhoosdMMMMMMMMMMMN/..-hMMMMMMMMMMMMMMh-++++MMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMNysohMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNMMMMMMMMMMMMMMMNyooohMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        ".colorize(:magenta)
        sleep (0.09)
        system 'clear'
    end

    def self.frame_four
        puts "
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmmNmddmMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMyyhddddhydMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdsoshhhhhyyhMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy+ohNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNsooohhhhhyyydMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmys-+odNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdsosyhhhhhyyhsmMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh/+/+ssmNMMMMMMMMMMMMMMMMMMMMMMMMMMMm+osyhdhhhhyyyysNMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMNmy/++++hNmNMMMMMMMMMMMMMMMMMMMMMMMMMMy++oydddhddyhyyyyNMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMmy++ooomNddMMMMMMMMMMMMMMMMMMMMMMNmNNyssohyhddmdhhhyhyhMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMNdoo://+++/+ydhdMMMMMMMMMMMMMMMMMMMMdhhhssysoooshdddyhhhyhsNMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMNs/:-:/:---:::::::/dMMMMMMMMMMMMMMMMMMmdhyysyssooosyhhhhhhhhyyhMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMN+-::/oo+/::-------:oMMMMMMMMMMMMMMMMMMmhhssyhhssysyyyyhhhyyyyysmMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMNs:::/++/ssso/::::-:/yMMMMMMMMMMMMMMMMMmyyyssyydyyyyssyyyyyyssysohMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMM/-::////+sysoo//+//+hMMMMMMMMMMMMMMMMMmssssyhhhhdhhhssyssssosyssohMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMo::://////+++++/+osoyMMMMMMMMMMMMMMMMMMhyysyhddddddhhyyyyyosysshodNMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMM:::///++//////://+++hMMMMMMMMMMMMMMMMMNhhhhhddmmmmmdhhhhyyhNmdmmmMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMhsooydo+////:::////+mMMMMMMMMMMMMMMMMMNdmmmmdddddddmmddhdNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMNNMMs+///////////+mMMMMMMMMMMMMMMMMMMNdmmmddhhhhddddhhMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMM+////////////+mMMMMMMMMMMMMMMMMMMMdhhhhhhhhhhhhysyMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMo/////////////yMMMMMMMMMMMMMMMMMMMdhhhhhhhhhhhhhyyhNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMm///////////////dMMMMMMMMMMMMMMMMMMhhhddhhhhhhhhyysohMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMo///////////////sMMMMMMMMMMMMMMMMMNsyyhddddddhhhyysssMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMd////:://:///////+NMMMMMMMMMMMMMMMMhyyyyhhdhhhhhhhysssMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMy/:///////////////hMMMMMMMMMMMMMMMMhyysyyhddhyyhyyysssMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMN/::::://////:::///oMMMMMMMMMMMMMMMMysyssyydmddhhyysssyMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMy:::////+os/////////mMMMMMMMMMMMMMMMyssssyydNmhhhhhyssdMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMM+::///++odm+//////+/yMMMMMMMMMMMMMMmsyssssdMMMmhhhhyssMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMd/::///++hMMy+/////+/oMMMMMMMMMMMMMMhyysssyNMMMMmdhhyyyMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMy/:///++sMMMm+/////+/+NMMMMMMMMMMMMNyyyssymMMMMMmdhyyyyMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMN/////++oNMMMMs+//+++++dMMMMMMMMMMMMhyyyyyhMMMMMMNdhhyyyMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMo////++odMMMMMh++/+++++dMMMMMMMMMMMmhddddhdMMMMMMMdhhhysNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMNh++//+osmMMMMMMh+++++++oNMMMMMMMMMMdhdmddmNMMMMMMMNdddhyyhMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMs/++++oyNMMMMMMMmo++++++oMMMMMMMMMMMmmmmddmMMMMMMMMmmmddhymMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMM+///+osNMMMMMMMMMho++++oyMMMMMMMMMMMmmmmddNMMMMMMMMNmmdddhmMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMm+//++smMMMMMMMMMMNso++oohMMMMMMMMMMMNmmmddMMMMMMMMMMNmdddddMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMh++/+sdMMMMMMMMMMMMyo++oomMMMMMMMMMMMNmmdmdMMMMMMMMMMNmdhddmMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMs+/+sdMMMMMMMMMMMMMdo+ossMMMMMMMMMMMMNmmmmmMMMMMMMMMMMmdhddNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMN+++ohMMMMMMMMMMMMMMmo+oohMMMMMMMMMMMd+odNmmMMMMMMMMMMMNdhdmMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMh++osNMMMMMMMMMMMMMMm+++/NMMMMMMMMMMm:.-omMMMMMMMMMMMMMmdhhmMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMN+++yNMMMMMMMMMMMMMMMm///:NMMMMMMMMMMs.+.sMMMMMMMMMMMMMMmdy+-dMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMy:::sMMMMMMMMMMMMMMMMh.---NMMMMMMMMMN-++.oMMMMMMMMMMMMMMNy/+.-mMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMM:.../MMMMMMMMMMMMMMMMhoosdMMMMMMMMMMM/...sMMMMMMMMMMMMMMMh-+++/MMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMdso+sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmMMMMMMMMMMMMMMMMNyooohMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        ".colorize(:magenta)
        sleep (0.09)
        system 'clear'
    end

    def self.frame_five
        puts "
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmddmmddmMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNssydddddydMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdsooyyhhdhyhMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNms/+yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy+ooyyhhhhyydMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMNmys+:odNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMsosyhhhhhhyhydMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMNmh+///+ymNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMds+shdhdhhyyyymMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMNmmy///o+ymmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd++oydhdhhyyyymMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMmhs++oosmNNmmNMMMMMMMMMMMMMMMMMMMMNmNNmdhsooohhhdhhyyyyyNMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMmdyo:/::/+//shhdMMMMMMMMMMMMMMMMMMMMmyyysssyssooshhddyhhyhyyMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMNs/::--...-:/:::---oNMMMMMMMMMMMMMMMMMMhhysosyhhs+osyhhhhhhysysMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMs----::-//:---:----:oMMMMMMMMMMMMMMMMMdyhs++syhhsssssyyhhyyyyyommMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMd:----://sso+/:::::--:mMMMMMMMMMMMMMMMdssssoosyydssyysyyyysssyyohhMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMM/---::/++syhyo+/////:sMMMMMMMMMMMMMMMdssssssshhyhdyhhssyssoosssoshMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMs:::://++/+o+++/+syssyMMMMMMMMMMMMMMMNhhyyyhhdmmmdddhhyyyyssmsydomNMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMs::///+++/////://osoMMMMMMMMMMMMMMMMMNhhhddmdddddmNmdhhyhhdMMNmMhNMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMNdysyo+++///::://+++MMMMMMMMMMMMMMMMMNddmmmmmhhhhhdmmdddmmMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMd++//:////////oMMMMMMMMMMMMMMMMMMMdydNmddhyhhhhdhhdMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMh//////://////+MMMMMMMMMMMMMMMMMMMMmddhhhhhhhhhhysdNMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMh//////////////dMMMMMMMMMMMMMMMMMMMhhhhhddhhhhhhyysyNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMo//////////////+MMMMMMMMMMMMMMMMMMNhhddhhhhhhhhhyysohMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMm////////////////hMMMMMMMMMMMMMMMMMmyyhhddddddhhhyyssyMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMy////:://:///////oMMMMMMMMMMMMMMMMMhsyyyhhdhhhhhhhysssMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMM+/////////////////mMMMMMMMMMMMMMMMMyyyyyhhdhhhhhyyyssoNMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMd//::::///+////:///yMMMMMMMMMMMMMMMMyyysyyhdmddhhhyssssMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMs/:::///++y+///////+NMMMMMMMMMMMMMMNsyyssyhdNmhhhhhyssyMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMM+//////++dNo//////++hMMMMMMMMMMMMMMmyyyysyhNMMmdhhhyysdMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMN//////++hMMh+/////+/sMMMMMMMMMMMMMMhyysssyNMMMMmdhhyysmMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMd/////++yMMMNo/////+/+NMMMMMMMMMMMMMyyyysymMMMMMNdhhyysNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMs/////+oNMMMMy+///++++yMMMMMMMMMMMNhyyyyydMMMMMMMdhhyysNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMh/////+omMMMMMm++//++++hMMMMMMMMMMMmhhhhhhmMMMMMMMddhhyshMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMd++///+smMMMMMMmo+++++++mMMMMMMMMMMhhddddmNMMMMMMMMdddhyysNMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMy//++++yMMMMMMMMMy++++++oNMMMMMMMMMmddmmddmMMMMMMMMNmmddhydMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMM+++//+sMMMMMMMMMMNoo+++osMMMMMMMMMMNmmmmddNMMMMMMMMMmmmddddMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMd+///+oNMMMMMMMMMMMdo+++ohMMMMMMMMMMMmmmmddMMMMMMMMMMNNmddddMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMs++++omMMMMMMMMMMMMmoo+oodMMMMMMMMMMMmmmdmmMMMMMMMMMMMNmhdddMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMm+///+dMMMMMMMMMMMMMNso+osMMMMMMMMMMMMmmdmmmMMMMMMMMMMMNmhddNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMs++/+hMMMMMMMMMMMMMMMsoooyMMMMMMMMMMNsydmmmmMMMMMMMMMMMMmhhdMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMm+//+sMMMMMMMMMMMMMMMMo+++NMMMMMMMMMM/.-omMNNMMMMMMMMMMMNmdhdMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMo/++smMMMMMMMMMMMMMMMM////NMMMMMMMMMd...+MMMMMMMMMMMMMMMNmdo:dMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMh--:/dMMMMMMMMMMMMMMMMh..--NMMMMMMMMM/.+++MMMMMMMMMMMMMMMMho..-mMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMm..../MMMMMMMMMMMMMMMMhoosdMMMMMMMMMM/.++:MMMMMMMMMMMMMMMMd-+++/MMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMy+//+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhhymMMMMMMMMMMMMMMMMNyooohMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM 
        ".colorize(:magenta)
        sleep (0.09)
        system 'clear'
    end

    def self.frame_six
        puts "
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhdhddddmMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmsoshhdddhdMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdos+syyhddydMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMNNd+:/yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMso++shyhhhhhdMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMNmmyoh:smNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMyssyydhhdhhhhmMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMNNNmd+/:/+smmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhhsoyyddhhyhymMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMNmmmy+//+oyNNdmMMMMMMMMMMMMMMMMMMMMMMMMMMMMmho+++ydhhhhhymMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMNhyo++++ohMMMNNMMMMMMMMMMMMMMMMMMMMmmNmdhyhys+oohddhhyyhymMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMNmds/:::.-///oyyhNMMMMMMMMMMMMMMMMMMMdyyyssoysysooshhmhhyhyysMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMs::----.---///::--/dMMMMMMMMMMMMMMMMMMyyssoo+oyhhsoosyhdhyhshsdMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMd:------::-::-------:ymMMMMMMMMMMMMMMMhsyyoosoooshhoooyhyhyysysyMmMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMo------:///so//:::::--:mMMMMMMMMMMMMMhssshyyysossdhsssyyyssssssoNhMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMM/-----:/++oyso+++///:::dMMMMMMMMMMMMmsysyysydhhdhhdhyyysyssosssoyhMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMN/:::::/++++/+++osyhso+dMMMMMMMMMMMMMhyyyyyhddddmddddhhyyyhyNyddyNNMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMs+///+++++///://oyNMNNMMMMMMMMMMMMMMhhhddhddhhhhhdmmdhhyyhmMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMNms++++///::://+omMMMMMMMMMMMMMMMMMmdddydmmdhhhhhhmmdddmNMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMN+++//:///////+mMMMMMMMMMMMMMMMMMMMmoymmddhyhhhhhhyNMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMM+////////////+dMMMMMMMMMMMMMMMMMMMMmhddhhhhhhhhyysdNMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMN//////////////oMMMMMMMMMMMMMMMMMMMNhhhhhddhhhyyyyyssNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMh///:///////////hMMMMMMMMMMMMMMMMMMNhhddhhhhhhhhhhysodMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMy///////////////+MMMMMMMMMMMMMMMMMMdyyhhdddddhhhhyyssyMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMM/////:://////////hMMMMMMMMMMMMMMMMMysyyyyhdhhhhhhhhsssMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMd/////////////////oMMMMMMMMMMMMMMMMMyyyyhhhddhhhhyyyssoNMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMs/////////+///////+NMMMMMMMMMMMMMMMMyyyyyyhmmdddhhyysssMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMM/////////+s++/////+hMMMMMMMMMMMMMMMNyyyyyyhdNmdhhhhyysyMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMN///////++yNo//////++MMMMMMMMMMMMMMMmyyyyyydNMMNdhhhyyshMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMd//////+oyMMy+/////+/hMMMMMMMMMMMMMMdyyyyyhNMMMMmdhhyysyMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMy/////++yMMMNo+////+/+NMMMMMMMMMMMMMyyyyyymMMMMMNddhyyshMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMM+/////+sMMMMMy++///+++hMMMMMMMMMMMMmyyyyyhMMMMMMMdhhhyssMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMd/////+sNMMMMMmo++/++++mMMMMMMMMMMMNhhhhhhNMMMMMMMddhhyyoNMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMho++//+yNMMMMMMNo+++++++NMMMMMMMMMMdyhhdhdmMMMMMMMMdddhyysmMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMy///+++sMMMMMMMMMho+++++oNMMMMMMMMMdhdddddNMMMMMMMMNmmddhhdMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMN+/+++/oMMMMMMMMMMMyo++++oMMMMMMMMMMmdmmmdmMMMMMMMMMMmmmdhddMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMy++///+mMMMMMMMMMMMmoo++oyMMMMMMMMMMmmmmddNMMMMMMMMMMNmmddddMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMN++++++dMMMMMMMMMMMMMoo++odMMMMMMMMMMNmmmdmNMMMMMMMMMMMNmdhddMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMy+++/+yMMMMMMMMMMMMMMso+osMMMMMMMMMMMmmmdmmNMMMMMMMMMMMNmdhdmMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMN++++/sMMMMMMMMMMMMMMMso+ohMMMMMMMMMMddmmmmmNMMMMMMMMMMMMmdhdMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMy+//++mMMMMMMMMMMMMMMMs+++NMMMMMMMMMs:-omNmmNMMMMMMMMMMMMmmhdMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMd//+++hMMMMMMMMMMMMMMMM////NMMMMMMMMN-..:mMMMMMMMMMMMMMMMMmmh/dMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMM:--:/oNMMMMMMMMMMMMMMMh..--NMMMMMMMMh.++-NMMMMMMMMMMMMMMMMys/.-mMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMs....+MMMMMMMMMMMMMMMMhoosdMMMMMMMMMo+++.hMMMMMMMMMMMMMMMMd-++++MMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMNs/::/MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs+++mMMMMMMMMMMMMMMMMNyooohMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        ".colorize(:magenta)
        sleep (0.09)
        system 'clear'
    end

    def self.frame_seven
        puts "
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhsyyhdddNMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMds+oshdddhdMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNyo+ooyhyddhmMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMNmd/:/hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMsssoshhydhhhmMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMNmdsoh+smmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmssyhhyyddhhhNMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMNNmmdo/::+sNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdddhososhhhhhNMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMNmmmdyo////+dMmmMMMMMMMMMMMMMMMMMMMMMMMMMMNmhhhh+o++hhdhhymMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMNhyo++/-:/sMMMMMMMMMMMMMMMMMMMMMMMNmmmdhssssyy+:/sdddhhhymMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMNdho/::/-.-:/+ssyNMMMMMMMMMMMMMMMMMMNsyysosssooo+sooyhdhhyyyymMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMy:--------:/--::--:yMMMMMMMMMMMMMMMMMdssysossyssosdyooydhhysyssNMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMM/--------:/:://:----+dmMMMMMMMMMMMMMMyssysssyyhyohdhsooyhyssssoyMmMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMm:--------:o+oo+//:::::/sMMMMMMMMMMMMdsosyysssyhhyyhdyssyyysoososNhMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMM+:--:--:/+so+o+oos////::NMMMMMMMMMMMssyssysshhhhddhhhyyysyyyysoyyhMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMd:::::://++////+sNms++odMMMMMMMMMMMmyyyyyhhydhhhhhmmdhyhyyhdMNmdNNMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMd+///////+//://+MMMmmNMMMMMMMMMMMMNhhhhdddddhhhyhdmmmhhyydMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMy////+////////+mMMMMMMMMMMMMMMMMMMNdddmhmmddhhhhhhddmmmNMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMNo/////////////dMMMMMMMMMMMMMMMMMMMMNNNddddhhhhhhysyMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMs/////////////yMMMMMMMMMMMMMMMMMMMMNdhhhhhhhhhhyyyyhNMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMM+/////////////+mMMMMMMMMMMMMMMMMMMMmhhhhhhhhhhyyyyssyMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMm////://////////oMMMMMMMMMMMMMMMMMMMmhhddhhhhhhhhhyysomMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMd////////////////dMMMMMMMMMMMMMMMMMMhyyhhdddddhhhhyysshMMMMMMMMMMMMMMMMMMMMMMM    
        MMMMMMMMMMMMMMMMMMMMMMy/////://////////sMMMMMMMMMMMMMMMMMNyyyyyyhdhhddhhhhssyMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMM+/////////////////NMMMMMMMMMMMMMMMMmyyyyhhhddhhdhhyyssyMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMd/////////++///////dMMMMMMMMMMMMMMMMNyyyyhhdmNmdddhhyssyMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMy////////++o++/////sMMMMMMMMMMMMMMMMNyyyyhhdmMmddhhhhyshMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMy//////+++sd+//////+mMMMMMMMMMMMMMMMmyyyyyhdNMMNmdhhhyshMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMs/////+++sNNo+//////sMMMMMMMMMMMMMMMdyyyyhdMMMMMmddhhyssMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMM+/////++sNMMd++///++/dMMMMMMMMMMMMMNyyyyyhNMMMMMNddhhysoNMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMN//////+sNMMMNo++///+++MMMMMMMMMMMMMNyyyyyhMMMMMMMdddhyssmMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMh/////+sNMMMMMho++/++++MMMMMMMMMMMMNhhhhhhNMMMMMMMdddhyysdMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMNy++++/+yNMMMMMMNo++++++oMMMMMMMMMMMdhhhhdhmMMMMMMMMmddhyyymMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMo/+++++oMMMMMMMMMdo+++++oMMMMMMMMMMdyhhdddmMMMMMMMMMmmddhhdMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMd+/+++++mMMMMMMMMMMyo++++sMMMMMMMMMMdddddddMMMMMMMMMMmmmhhddMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMo+++//+hMMMMMMMMMMMmoo+++hMMMMMMMMMMddmmddNMMMMMMMMMMNmmdhdhMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMm+++++/oMMMMMMMMMMMMNoo++odMMMMMMMMMMmmmdddMMMMMMMMMMMMNmdhddMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMs++++/+mMMMMMMMMMMMMMso++oMMMMMMMMMMNmmdddmMMMMMMMMMMMMMmmhdmMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMm++++++hMMMMMMMMMMMMMNso++yMMMMMMMMMNmddddmNMMMMMMMMMMMMMmmdhNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMs+++++sMMMMMMMMMMMMMMMs+++mMMMMMMMMmo/sdmmmNMMMMMMMMMMMMMNmdhMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMh//++++mMMMMMMMMMMMMMMM/://mMMMMMMMMo..:yMNNMMMMMMMMMMMMMMdddsdMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMM:--:/+hMMMMMMMMMMMMMMMh...-NMMMMMMMM/.`.sMMMMMMMMMMMMMMMMMso/--mMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMs....oMMMMMMMMMMMMMMMMhoosdMMMMMMMMM-+++.NMMMMMMMMMMMMMMMMh-+++/MMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMNo:::/MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd+//+NMMMMMMMMMMMMMMMMNyooohMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        ".colorize(:magenta)
        sleep (0.09)
        system 'clear'
    end

    def self.frame_eight
        puts "
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmNmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdysohhdddNMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMddso+oydhddNMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMNmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmyo+ooydhhdhmMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMNmmh/++dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNyossoymhhdhyNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMNNmdsoy+odNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmysyhhhhys+sdMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMNNNmddo/::+oodMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmdddddoy++oshdMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMmmNmdho+++/-/yMMMMMMMMMMMMMMMMMMMMMMMMMMMNhsyyhhho///+hhhhNMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMNyso+++-.-/yMMMMMMMMMMMMMMMMMMMMMMmmmmhsossooooo++odddhyydNMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMNdy+:::/o+--:/osyNMMMMMMMMMMMMMMMMMMhsyysoossssssssys+hmhyyyysmMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMm:------::--//--:::yNMMMMMMMMMMMMMMMMyssyooosyysyyyyhsoshhysysohNMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMy:------:---/+//+/::/ydNMMMMMMMMMMMMMysssyssssssyyyyhhsyoyssssoyyMmMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMh:---------:o++/+o+////+hMMMMMMMMMMMMooosyysossyhyhdhhyysyysoooNsNhMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMs:::--:-:/++///ohs+/////NMMMMMMMMMMNsyysyyyyyhhhhhdddhhyyyyhmhMyyhMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMo/:::://///////dNyo++odMMMMMMMMMMMmyyyyyyhyyhhhhyhdmddyyssmMMMdNNMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMd+/////////////dMMNmmNMMMMMMMMMMMMMhyhhhddhhddhhhhhddmdddmMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMm++////////////mMMMMMMMMMMMMMMMMMMMNmdmmmmddhhhhyhyshMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMs/////////////dMMMMMMMMMMMMMMMMMMMMMMNmddhhhhyyyyyshNMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMh/////////////sMMMMMMMMMMMMMMMMMMMMMNhhhhhhhhhhhyyssyMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMy//////////////hMMMMMMMMMMMMMMMMMMMMdhhhhhhhhhhhyyysodMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMN+////://///////+NMMMMMMMMMMMMMMMMMMMhhhhddhhhhhdhyyyssMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMN////////////////yMMMMMMMMMMMMMMMMMMNyhhyhhdddddhhhhysoMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMm//////://///////+NMMMMMMMMMMMMMMMMMmyyyhyyyddhdddhhhsoNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMs//////////+///://hMMMMMMMMMMMMMMMMMdyyyyyhhdmddddhhysomMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMN/////////+++//////sMMMMMMMMMMMMMMMMMdyhyhhhdmNmddddhyysmMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMm////////+++o++////+MMMMMMMMMMMMMMMMMdyyhhhddNMmddhhhhysNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMd///////+++hs+//////dMMMMMMMMMMMMMMMMdyyhhhhmMMMNmddhhysmMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMm//////++odMh++/////+NMMMMMMMMMMMMMMMhyhhhhdMMMMMmddhhysyMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMm/////++odMMMs++/////sMMMMMMMMMMMMMMmyyyyhhNMMMMMNddhhyssMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMy////++odMMMMho++///++mMMMMMMMMMMMMMmyyyhydMMMMMMNdddhyssNMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMNs////++dMMMMMNs+++++++hMMMMMMMMMMMMmhhhhhhNMMMMMMMdddhyysdMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMho++++++sMMMMMMMmo++++++hMMMMMMMMMMMmhhhhdhmMMMMMMMMmdddhyyNMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMm/+++++o+mMMMMMMMMho+++++hMMMMMMMMMMdyhhddddMMMMMMMMMmmddhhhMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMy/++++++yMMMMMMMMMNso++++hMMMMMMMMMMhhdddddNMMMMMMMMMNmmdhhhMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMN++++/++oNMMMMMMMMMMhoo+++dMMMMMMMMMNddmmddmMMMMMMMMMMMmmdhdhMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMh+++++++mMMMMMMMMMMMmoo++oNMMMMMMMMMNdmmdddMMMMMMMMMMMMNmmhddMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMo++++++hMMMMMMMMMMMMmoo++oMMMMMMMMMMmmmdhdNMMMMMMMMMMMMMmmdhmMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMd++++++sMMMMMMMMMMMMMmo+++yMMMMMMMMMMdddhdmMMMMMMMMMMMMMMNmdhNMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMs++/++omMMMMMMMMMMMMMMo+++yMMMMMMMMdsshddmNMMMMMMMMMMMMMMNmdhMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMd///+++yMMMMMMMMMMMMMMN::/+dMMMMMMMM+.:odmNMMMMMMMMMMMMMMMhhdhmMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMM:--:/syNMMMMMMMMMMMMMMy...-MMMMMMMMM-..-dMMMMMMMMMMMMMMMMMs+:--mMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMo....oMMMMMMMMMMMMMMMMh+osdMMMMMMMMM-+++-NMMMMMMMMMMMMMMMMh-+++/MMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMmo:::/MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMho++oNMMMMMMMMMMMMMMMMNyooohMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        ".colorize(:magenta)
        sleep (0.09)
        system 'clear'
    end

    def self.animation
        5.times do
            Gif.frame_one
            Gif.frame_two
            Gif.frame_three
            Gif.frame_four
            Gif.frame_six
            Gif.frame_seven
            Gif.frame_eight
        end
    end

    def self.go
        system 'clear'
        self.animation
        puts "\n\n 🚴‍♀️🍉 Activity complete. Way to go! 🏃🍅 \n\n".colorize(:red)
    end
  
end 